<img style="float: right;" src="resources/img/lll_logo.png" width=160 height=160 />
 
# Einführung in Python 

Dieses Übungsblatt ist eine kurze Einführung in Python und bietet dir eine Übersicht über die wichtigsten Punkte, die du für den KI-Workshop benötigst. <br>
Das Übungsblatt ist ein Jupyter Notebook. Es besteht aus Felder, die Text beinhalten und nicht ausführbar sind, und aus Felder in denen ausführbarer Code geschrieben ist. <br><br>

<img style="float: left;" src="resources/img/laptop_icon.png" width=50 height=50 /> <br><br>
Führe das untere Feld aus, indem du das Feld per Klick auswählst und entweder oben in der Leiste auf <b><i>Run</i></b> klickst oder <b><i>Str</i></b> gedrückt hälst und auf <b><i>Enter</i></b> drückst.


In [50]:
# Das ist ein ausführbares Feld.
# Zeilen, die mit dem Symbol # beginnen, werden vom Compiler ignoriert. 
# Du kannst # also dafür nutzen, um Kommentare zu schreiben.

print("Herzlich Willkommen im Lehr-Lern-Labor Informatik am KIT!")

Herzlich Willkommen im Lehr-Lern-Labor Informatik am KIT!


## Einrückungen

Im Gegensatz zu solchen Programmiersprachen wie <i>C</i> oder <i>Java</i> werden in Python keine geschweiften Klammern verwendet, um das Programm zu strukturieren. Die ganze Strukturierung von Klassen, Anweisungen oder Funktionen basiert auf Einrückungen. Wenn du eine Anweisung schreibst und eine Einrückung vergisst, kann sich dein Programm anders verhalten als von dir gewollt. Achte also im Folgenden penibel darauf, welcher Code eingerückt werden muss.

## Wichtige Datentypen

Aus dem Informatikunterricht kennst du vielleicht schon verschiedene Datentypen: <i>integer, double, string</i>, usw. <br> Bei vielen Programmiersprachen musst du bei der Deklaration einer Variablen angeben, um welchen Datentypen es sich handelt. <br>In Python ist das nicht erforderlich, da der Compiler selbst bei der Ausführung entscheidet, welcher Datentyp für eine Variable am sinnvollsten ist. <br><br>

<img style="float: left;" src="resources/img/laptop_icon.png" width=50 height=50 /> <br><br>
Ergänze die fehlenden Variablen passend, sodass die Ausgabe fehlerfrei ist. <br>
(Hinweis: Boolsche Werte nehmen in Python entweder den Wert <i>True</i> oder <i>False</i> an.)

In [14]:
steckbrief = "Steckbrief:\n"
name = "Max"
maennlich = True
alter = 15
groesse = 1.71

print(steckbrief, "Name: ", name, "\n", "männlich:", maennlich, 
      "\n", "Alter: ", alter, "\n", "Größe (in m): ", groesse)

Steckbrief:
 Name:  Max 
 männlich: True 
 Alter:  15 
 Größe (in m):  1.71


<img style="float: left;" src="resources/img/laptop_icon.png" width=50 height=50 /> <br><br>
Bearbeite die folgenden beiden Felder, um den Umgang mit elementaren Datentypen in Python zu üben.

In [14]:
from resources.code.help_functions import pruefe_eingabe

# Ergänze unter jedem nachfolgenden Kommentar deinen Code.
x = 9

# Addiere zur Variable 'x' 6 dazu.
x += 6

# Multipliziere das Ergebnis mit 3. 
x *= 3

# Nehme das Ergebnis hoch 4 (Hochzeichen: **).
x = x**4

# Teile das Ergebnis durch 91125.
x //= 91125

# Subtrahiere 3 vom Ergebnis.
x -= 3

pruefe_eingabe(x)

Du hast alles richtig gemacht! Das Ergebnis ist 42


In [2]:
begruessung1 = 'hi'
begruessung2 = 'hallo'
begruessung3 = 'hey'

# Konkateniere alle Begrüßungen indem du die oberen String jeweils durch ein '+' verbindest
# und das Ergebnis mit der Variable 'begruessung' gleichsetzt.

begruessung = begruessung1 + begruessung2 + begruessung3
print("Konkatierter String: ", begruessung)

# Gebe den dritten und siebten Buchstaben der Variable 'begruessung' aus und überprüfe dein Ergebnis selbst. 
# Möchtest du den i-ten Buchstaben eines Strings str ausgeben lassen, schreibst du einfach str[i].
# (Beachte, dass Informatiker von 0 anfangen zu zählen!)

print("Dritter Buchstabe:", begruessung[2] + ",", "Siebter Buchstabe:", begruessung[6])

# Du kannst nicht nur einzelne Buchstaben eines Strings ausgeben lassen, sondern bestimmte Bereiche.
# Möchtest du von einem String str z.B. den Bereich vom fünften bis ausschließlich zum achten String ausgeben 
# lassen, machst du das durch str[5:8]. 
# Möchtest du den Bereich von Anfang bis ausschließlich dem vierten Buchstaben erhalten, 
# schreibst du str[0:4] oder str[:4]. 
# Analog schreibst du str[4:], wenn du den Bereich vom vierten bis zum letzten Buchstaben
# erhalten möchtest.

# Benutze deine vorher definierte Variable 'begruessung', um hi, hallo und hey mithilfe [] ausgeben zu lassen.
print(begruessung[:2])
print(begruessung[2:7])
print(begruessung[7:])


Konkatierter String:  hihallohey
Dritter Buchstabe: h, Siebter Buchstabe: o
hi
hallo
hey


## Kontrollstrukturen

Möchtest du in Python den Ablauf deines Programms steuern, verwendest du Kontrollstrukturen so wie in den Programmiersprachen, die du schon gewohnt bist. Nur die Syntax unterscheidet sich ein wenig. Im Folgenden findest du immer ein Beispiel von einer Kontrollstruktur in einem ausführbaren Feld gefolgt von einer Aufgabe, bei der du das Gezeigte direkt anwenden sollst. 

### if-else-Anweisung

In [52]:
# Führe das folgende Feld aus. 
# Beobachte, was passiert, wenn du die Wert änderst.

bedingung = True

# Klammern sind bei einer if-else-Anweisung um die Bedingung optional.
if bedingung:
    print("Die Bedingung ist erfült.")
else:
    print("Die Bedingung ist nicht erfüllt.")
    
x = 5

if (x < 0):
    print("Die Zahl ist kleiner 0.")
elif (0 <= x <= 3):
    print("Die Zahl liegt zwischen 0 und 3.")
else:
    print("Die Zahl ist größer als 5.")
    
name1 = 'Angela'
name2 = 'Olaf'

# Eine elif- oder else-Anweisung muss nicht zwingend nach einer if-Anweisung folgen.
if name1 == 'Angela':
    print("Hallo Angela!")
    
if name1 != name2:
    print("{} und {} sind zwei unterschiedliche Namen.".format(name1, name2))

Die Bedingung ist erfült.
Die Zahl ist größer als 5.
Hallo Angela!
Angela und Olaf sind zwei unterschiedliche Namen.


<img style="float: left;" src="resources/img/laptop_icon.png" width=50 height=50 /> <br><br>
Realisiere folgenden Sachverhalt: <br>

<i>Wenn der eingeloggte Benutzer Jana ist, dann soll sie zunächst begrüßt werden. Wenn sie das Passwort richtig eingeben hat (verwende für das Passwort eine boolsche Variable), dann soll ihr aktueller Punktestand von 2241 Punkten ausgegeben werden. Wenn sie das Passwort falsch eingegeben hat, dann soll das ausgegeben werden. Wenn der eingeloggte Benutzer Ramon ist, dann ist der Ablauf analog zum oberen Fall, wobei sein aktueller Punktestand 2110 beträgt. Wenn der eingeloggte Benutzer weder Jana noch Ramon ist, dann soll ausgegeben werden, dass der Nutzername nicht bekannt ist. 

In [9]:
# Füge hier deinen Code ein.
eingeloggterBenutzer = 'Ramon'
passwort = True

if eingeloggterBenutzer == 'Jana':
    print("Hallo Jana!")
    if passwort:
        print("Du bist eingeloggt! Dein aktueller Punktestand beträgt 2241.")
    else:
        print("Du hast das Passwort falsch eingegeben!")

elif eingeloggterBenutzer == 'Ramon':
    print("Hallo Ramon!")
    if passwort:
        print("Du bist eingeloggt! Dein aktueller Punktestand beträgt 2110.")
    else:
        print("Du hast das Passwort falsch eingegeben!")
        
else:
    print("Dieser Nutzername ist leider nicht bekannt.")
        

Hallo Ramon!
Du bist eingeloggt! Dein aktueller Punktestand beträgt 2110.


### while-Schleife
Der Code in der while-Schleife wird solange ausgeführt, bis die Bedingung der while-Schleife nicht mehr erfüllt ist. Wenn die Bedingung nie auf <i>falsch</i> gesetzt wird, dann wird die while-Schleife unendlich oft ausgeführt und dein Programm wird nie regulär beendet. 

In [13]:
i = 0
while i < 5:
    print("i=", i)
    i += 1

i= 0
i= 1
i= 2
i= 3
i= 4


<img style="float: left;" src="resources/img/laptop_icon.png" width=50 height=50 /> <br><br>
Berechne mithilfe der while-Schleife die Summe von 1 bis 10.



In [2]:
# Füge hier deinen Code ein
i = 1
ergebnis = 0

while (i < 10):
    ergebnis += i
    i += 1
    
print(ergebnis)

45


### for-Schleife
Möchtest du über einen Zahlenbereich (ganzer Zahlen), ein String oder allgemein über ein iterierbares Objekt iterieren, so eignet sich die for-Schleife dazu. 

In [32]:
# So iterierst du über den Zahlenbereich (ganzer Zahlen) von 0 bis aussschließlich 3.
for i in range(3):
    print("{}. Hallo".format(i))
    
# So iterierst du über den Zahlenbereich (ganzer Zahlen) von 5 bis aussschließlich 10.
for i in range(3,6):
    print("{}. Hi".format(i))
    
# So iterierst du über einen String.
str = 'ABCDE'
for s in str:
    print(s)

0. Hallo
1. Hallo
2. Hallo
3. Hi
4. Hi
5. Hi
A
B
C
D
E


<img style="float: left;" src="resources/img/laptop_icon.png" width=50 height=50 /> <br><br>
Zähle mit Hilfe einer for-Schleife und einer if-Anweisung die Vorkommen des Bustaben 'a' im vorgegebenen Satz. Anschließend kannst du mit <i>satz.count('a')</i> überprüfen, ob du richtig liegst.

In [49]:
satz = "Max wachst Wachsmasken. Was macht Max? Wachsmasken wachst Max."
anzahl = 0
for s in satz:
    if s is 'a':
        anzahl += 1
        
print("Anzahl der a's:", anzahl)

print("Richtiges Ergebnis:", satz.count('a'))

Anzahl der a's: 11
Richtiges Ergebnis: 11


## Sequentielle Datentypen

Du hast mit dem Datentyp <i>String</i> bereits einen sequentiellen Datentyp in Python kennengelernt. Im Folgenden betrachten wir weitere sequentielle Datentypen.

### Tupel

In Tupeln kannst du mehrere Informationen speichern. Einmal definiert, können die Werte in einem Tupel nicht mehr verändert werden.

In [4]:
# Tupel definierst du mit Hilfe von runden Klammern ().
sheldon = ('Sheldon', 'Cooper', '26.Februar 1980', 'Theoretischer Teilchenphysiker')
leonard = ('Leonard', 'Leakey Hofstadter', '17.Mai 1980', 'Experimentalphysiker')
amy = ('Amy', 'Farrah Fowler', '17. Dezember', 'Neurobiologin')


# Mithilfe von eckigen Klammern greifst du auf die unterschiedlichen Einträge zu.
print(f"{amy[0]} {amy[1]} ist {amy[3]}.")


Amy Farrah Fowler ist Neurobiologin.


### Listen

Du kannst mit Hilfe von Listen mehrere Inhalte speichern, so wie du das oben bei Tupeln gesehen hast. Allerdings kannst du im Gegensatz die Inhalte in Listen verändern, hinzufügen und löschen.

In [6]:
# Listen wird mit Hilfe von eckigen Klammern definiert.
farben = ["rot", "grün", "gelb", "blau", "lila", "pink", "orange"]

# So iterierst über eine Liste.
for farbe in farben:
    print("Farbe: ", farbe)
    
# Du kannst auch durch einen bestimmten Index i Elemente in der Liste ansprechen: name_der_liste[i].
print("Die Farbe '{}' steht in der Liste an dritter Stelle.".format(farben[2]))

# Durch den Index -1 wird dir das letzte Element zurückgegeben, mit dem Index -2 das vorletzte, usw.
print("'{}' ist das letzte und '{}' das vorletzte Elemente der Liste.".format(farben[-1], farben[-2]))

# Mit dem Befehl name_der_liste.pop() wird dir das zuletzt hinzugefügte Element zurückgegeben und entfernt.
# Gibst du in der Klammer eine Zahl i an, so wird das i-te Element der Liste zurückgegeben und entfernt.
print("Die Farbe '{}' wurde entfernt.".format(farben.pop()))
print("Die Farbe '{}' wurde entfernt.".format(farben.pop(3)))

# Wenn ein Element entfernt werden soll, verwendest du den Befehl name_der_liste.remove(inhalt). 
farben.remove('rot')

# Mit dem Befehl name_der_liste.append() hängst du ein neues Element an die Liste.
farben.append('türkis')
# alternativ:
farben = farben + ['burgund']

# Du kannst sogar Listen an andere Listen anhängen. 
# Hiefür verwendest du den Befehl name_der_liste.extend(andere_Liste).
farben2 = ["beige", "magenta", "khaki"]
farben.extend(farben2)
 
print(farben)

# Eine Liste muss nicht zwingend Objekte vom gleichen Datentyp beinhalten.
liste = [1.3, 'rot', 42, ['Lea', 'Frank', 'Ali']]


Farbe:  rot
Farbe:  grün
Farbe:  gelb
Farbe:  blau
Farbe:  lila
Farbe:  pink
Farbe:  orange
Die Farbe 'gelb' steht in der Liste an dritter Stelle.
'orange' ist das letzte und 'pink' das vorletzte Elemente der Liste.
Die Farbe 'orange' wurde entfernt.
Die Farbe 'blau' wurde entfernt.
['grün', 'gelb', 'lila', 'pink', 'türkis', 'burgund', 'beige', 'magenta', 'khaki']


<img style="float: left;" src="resources/img/laptop_icon.png" width=50 height=50 /> <br><br>
Eine Fibonacci-Zahl ist gleich der Summe ihrer beiden Vorgänger, wobei die erste Zahl gleich 0 und die zweite Zahl gleich 1 sind. In der Liste 'fibonacci' sind die ersten beiden Zahlen bereits abgespeichert. Führe diese Liste solange fort bis 15 Zahlen in dieser Liste sind und überprüfe dein Ergebnis.

In [1]:
from resources.code.help_functions import pruefe_fibonacci

fibonacci = [0, 1]

for i in range(13):
    fibonacci.append(fibonacci[-1] + fibonacci[-2])
    
pruefe_fibonacci(fibonacci)

Super! Das sind die ersten 15 Fibonacci-Zahlen: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377]


### Dictionaries
Abgesehen von Listen, Strings und Tupeln gibt es in Python noch einen weiteren wichtigen sequentiellen Datentyp: <i>Dictonaries</i> (in anderen Programmierspachen auch als <i>Maps</i> oder <i>Hashs</i> bezeichnet). Dabei wird immer ein Schlüssel-Objekt-Paar abgespeichert, so dass man analog zu einem Wörterbuch nach einem Schlüssel suchen kann und das entsprechende Objekt zurückgegeben wird.

In [39]:
# Eine Dictionary wird durch geschweifete Klammern gekennzeichnet. 
# Nach der Eingabe des Schlüssels folgt ein Doppelpunkt gefolgt von dem Objekt, 
# das mit diesem Schlüssel assoziiert werden soll. 
dictionary = {'animal': 'Tier', 'ball': 'Ball', 'chicken': 'Hähnchen', 'door': 'Tür'}

# Möchtest du das Objekt für einen bestimmten Eintrag erhalten, schreibst du das wie folgt:
print("Eintrag für 'door':", dictionary['door'])

# So kannst du weitere Einträge zu der Dictionary hinzufügen.
dictionary['egg'] = 'Ei'

# Fügst du für einen bereits vorhandenen Schlüssel einen weiteren Eintrag hinzu,
# so wird der alte Eintrag überschrieben.
dictionary['chicken'] = 'Hühnchen'

# So iterierst du über alle Schlüssel der Dictionary:
for key in dictionary:
    print("Schlüssel: {} --> Objekt: {}".format(key, dictionary[key]))
    
# So iterierst du über alle Objekte der Dictionary:
print("Alle Objekte in der Dicionary:", end=" ")
for value in dictionary.values():
    print(value, end=". ")
print()

# So erstellt du eine leere Dictionary, der du später Einträge hinzufügen kannst:
leere_dictionary1 = {}
# alternativ:
leere_dictionary2 = dict()
print("Leere Liste 1:", leere_dictionary1, "leere Liste 2:", leere_dictionary2)
    
# Du kannst durch die Funktion zip(liste1, liste2) aus zwei Listen liste1 und liste2 eine Dictionary erstellen.
laender = ['Deutschland', 'Frankreich','Niederlande', 'Spanien']
hauptstaedte = ['Berlin', 'Paris','Amsterdam',  'Madrid']
zuordnung = dict(zip(laender, hauptstaedte))
print(zuordnung)

Eintrag für 'door': Tür
Schlüssel: animal --> Objekt: Tier
Schlüssel: ball --> Objekt: Ball
Schlüssel: chicken --> Objekt: Hühnchen
Schlüssel: door --> Objekt: Tür
Schlüssel: egg --> Objekt: Ei
Alle Objekte in der Dicionary: Tier. Ball. Hühnchen. Tür. Ei. 
Leere Liste 1: {} leere Liste 2: {}
{'Deutschland': 'Berlin', 'Frankreich': 'Paris', 'Niederlande': 'Amsterdam', 'Spanien': 'Madrid'}


<img style="float: left;" src="resources/img/laptop_icon.png" width=50 height=50 /> <br><br>
Kodiere den gegebenen Ausdruck in Morse-Code und lasse deine Morse-Code prüfen. Dekodiere anschließend den gegebenen Morse-Code.

In [1]:
from resources.code.help_functions import morse, pruefe_kodiertes_wort, pruefe_dekodiertes_wort

# Die Variable 'morse' ist eine Dictionary. 
# Für jeden Großbuchstaben, Umlaut, Ziffer, Punkt, Komma und Leerzeichen 
# gibt es einen entsprechenden Eintrag in Morse-Code. 
morse = morse()

ausdruck = "KÜNSTLICHE INTELLIGENZ"
codiertes_wort = ""

for buchstabe in ausdruck:
    codiertes_wort += " " + morse[buchstabe]
    
pruefe_kodiertes_wort(codiertes_wort)

morse_code = '-. . ..- .-. --- -. .- .-.. . ... / -. . - --..'

buchstaben = [x for x in morse]
buchstaben_in_morse_code = [x for x in morse.values()]
morse = dict(zip(buchstaben_in_morse_code, buchstaben))

ergebnis = ""

einzelne_morse_zeichen = morse_code.split(" ")

for elem in einzelne_morse_zeichen:
    ergebnis += morse[elem] 

pruefe_dekodiertes_wort(ergebnis)

1.Aufgabe: Richtig! Der Morsecode lautet: 
  -.- ..-- -. ... - .-.. .. -.-. .... . / .. -. - . .-.. .-.. .. --. . -. --.. 

2.Aufgabe: Richtig! Das dekodierte Wort lautet: NEURONALES NETZ


## Funktionen 

Um u.a. nicht jedes Mal bestimmten Code aufs Neue schreiben zu müssen, definiert man in Python (sowie in allen anderen Programmiersprachen) Funktionen. Diese können an den passenden Stellen aufgerufen werden, sodass der Code übersichtlich bleibt. <br><br>
Angenommen man möchte an einer Stelle im Programmcode die Summe von <i>a</i> und bis <i>b</i> berechnen und an einer anderen Stelle die Summe von <i>c</i> bis <i>d</i>. Anstatt zweimal den selben Code zu schreiben, kann man eine Funktion definieren, die die Summe der Zahlen zwischen zwei bestimmten Zahlen berechnet.

In [14]:
# Mit dem Schlüsselwort def definierst du eine Funktion.
# Der Name deiner Funktion ist (bis auf bestimmte Einschränkungen) frei wählbar.
# In den runden Klammern schreibst du deine Paramter, dabei brauchst du nicht anzugeben, 
# um welche Datentypen es sich handelt.
# Außerdem brauchst du nicht anzugeben, ob die Funktion einen Wert zurückgibt oder nicht.

# Berechnet die Summe von 'untere_grenze' bis einschließlich 'obere_grenze'.
def summe(untere_grenze, obere_grenze):
    rueckgabewert = 0
    for i in range(untere_grenze, obere_grenze+1):
        rueckgabewert += i
    return rueckgabewert

# Jetzt können wir die Funktion so oft aufrufen, wie wir es für sinnvoll halten.
print(f"Summe von 1 bis 10: {summe(1, 10)}")
print(f"Summe von 110 bis 120: {summe(110, 120)}")



Summe von 1 bis 10: 55
Summe von 110 bis 120: 1265


<img style="float: left;" src="resources/img/laptop_icon.png" width=50 height=50 /> <br><br>
Schreibe eine Funktion, die als Parameter einen Index <i>i</i> erhält und die i-te Fibonacci-Zahl zurückgibt.

In [25]:
def func_fibonacci(i):
    ergebnis = 0
    if i == 0:
        return 0
    elif i == 1:
        return 1
    else:
        return func_fibonacci(i-1) + func_fibonacci(i-2)
    
print(f"3-te Fibonacci-Zahl: {func_fibonacci(2)}, 10-te Fibonacci-Zahl: {func_fibonacci(9)}, " + 
      f"20-te Fibonacci-Zahl {func_fibonacci(19)}")

3-te Fibonacci-Zahl: 1, 10-te Fibonacci-Zahl: 34, 20-te Fibonacci-Zahl 4181


## Klassen

In [39]:
# Eine Klasse wird durch das Schlüsselwort 'class' gekennzeichnet.
class Person:
    
    # So wird der Konstruktur einer Klasse definiert.
    # Beachte, dass der erste Parameter jeder Funktion immer 'self' ist.
    def __init__(self, name, alter, wohnort):
        self.name = name
        self.alter = alter
        self.wohnort = wohnort
        
    def gebe_name_zurueck(self):
        return self.name
    
    def gebe_alter_zurueck(self):
        return self.alter
    
    def gebe_wohnort_zurueck(self):
        return self.wohnort
    
    def geburtstag(self):
        self.alter += 1
    
    def umziehen(self, neuer_wohnort):
        self.wohnort = neuer_wohnort

# Ein Objekt der Klasse 'Person' wird erstellt
luca = Person("Luca", 15, "Karlsruhe")

luca.geburtstag()
luca.umziehen("Freiburg")

print(f"{luca.gebe_name_zurueck()} ist {luca.gebe_alter_zurueck()} Jahre alt " + 
      f"und wohnt in {luca.gebe_wohnort_zurueck()}")



Luca ist 16 Jahre alt und wohnt in Freiburg


<img style="float: left;" src="resources/img/laptop_icon.png" width=50 height=50 /> <br><br>
Schreibe eine Klasse, die einen Getränkeautomaten simulieren soll. Der Automat soll die Attribute 'an' und 'konto' haben. Folgende Methoden sollen in der Klasse implementiert werden: <i>anschalten, ausschalten, muenze_einwerfen</i> und <i>getraenk_ausgeben</i>. Der Automat soll genau dann ein Getränk ausgeben und den Kontostand um zwei Münzen verkleinern, wenn er eingeschaltet ist, mehr als zwei Münzen auf dem Kontostand sind und die Methode <i>getraenk_ausgeben</i> aufgerufen wird.

In [5]:
# Füge hier deinen Code ein.
class Getraenkeautomat:
    def __init__(self, an, konto):
        self.an = an
        self.konto = konto
    
    def anschalten(self):
        self.an = True
        
    def ausschalten(self):
        self.an = False
        
    def muenze_einwerfen(self):
        self.konto += 1
        
    def getraenk_ausgeben(self):
        if self.konto >= 2 and self.an:
            self.konto -= 2
            print("Getränk wurde ausgegeben.")
        else:
            print("Der Automat ist entweder nicht eingeschaltet oder der Kontostand ist zu niedrig.")

            
automat = Getraenkeautomat(False, 0)
automat.anschalten()
automat.muenze_einwerfen()
automat.getraenk_ausgeben()
automat.muenze_einwerfen()
automat.getraenk_ausgeben()


Der Automat ist entweder nicht eingeschaltet oder der Kontostand ist zu niedrig.
Getränk wurde ausgegeben.


## Importe

Möchtest du auf Code anderer Dateien oder auf deine lokalen Bibliotheken zugreifen, musst du sie vorher in dein Programm importieren. Danach kannst du auf die Funktionen des importierten Moduls zugreifen.

In [7]:
# Importe schreibst du überlicherweise am Anfang deines Programms auf.
import time
print("Heute:", time.asctime())

# Durch den Schlüsselbegriff 'as' kannst du dem  
# Import einen eigenen Namen geben.
import os.path as p
import os

# Gibt den aktuellen Pfad aus.
p.abspath(os.getcwd())

# Wenn du nur etwas Bestimmtes aus einer Datei 
# impotieren möchtest, kannst du das wie folgt tun:
from datetime import date

# Gibt den Wochentag (als Integer) eines Datums zurück.
date(2021, 11, 2).weekday()

# Du kannst auch deine eigenen Dateien in dein Programm importieren.
# Wenn du eine Datei von einem Ordner in deinem aktuellen Verzeichnis
# importieren möchtest, gibst du den relativen Pfad durch Punkte getrennt an:
from resources.code.help_functions import sagHallo

sagHallo()

Heute: Mon Nov  1 18:19:59 2021
Hallo! Das ist eine importierte Funktion.


## Fehlerbehandlung

Um zu verhindern, dass dein Programm bei einem Fehler während der Ausführung abstürzt, muss du festlegen, was in solch einem Fall passiert.

In [11]:
# Führe dieses Feld aus und ändere anschließend den Wert für 'y' und 
# beobachte, was bei der Ausführung passiert.
x = 1
y = 0
ergebnis = 0

try:
    ergebnis = x / y
except:
    print("Hier ist etwas schief gelaufen.")
finally:
    print("Dieser Block wird immer ausgeführt.")
    
print(f"ergebnis={ergebnis}")

Hier ist etwas schief gelaufen.
Dieser Block wird immer ausgeführt.
ergebnis=0


## Numpy

Numpy ist eine sehr mächtige Bibliothek, die viele numerische und mathematische Funktionen bereithält. <br>
Im Folgenden findest du ein paar Anwendungsbeispiele. Weitere Infos kannst du unter folgender URL nachlesen: https://www.python-kurs.eu/numpy.php. 

In [38]:
import numpy as np

# Definition einer 3 x 3 - Matrix
a = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
print("a=\n", a)

# Definition einer 3 x 3 - Matrix, deren Einträge ausschließlich 1 sind.
b = np.ones((3, 3), dtype=int)
print("b=\n", b)

# Addition zweier Matrizen gleicher Dimensionen.
print("a+b=\n", a+b)

# Definition einer 4 x 4 - Matrix, deren Einträge ausschließlich 0 sind.
c = np.zeros((4, 4), dtype=int)
print("c=\n", c)

# Form der Matrix verändern:
c = c.reshape((2, 8))
print("c_neu=\n", c)

# Eine Matrix, die als Einträge nur Einsen hat und die gleiche Form wie die Matrix 'c' besitzt.
d = np.ones_like(c)
print("d=\n", d)

a=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b=
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
a+b=
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
c=
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
c_neu=
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
d=
 [[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


## Mini-Aufgaben


### Zahlen sortieren

<img style="float: left;" src="resources/img/laptop_icon.png" width=50 height=50 /> <br><br>

Schreibe eine Funktion, die eine beliebige Liste von Zahlen aufsteigend sortiert und die sortierte Liste zurückgibt.


In [ ]:
unsortierte_liste = [-2, 45, -102, 231, 89, -73, 42, 0, 99, 123, -11]

# Füge deinen Code hier ein.

### Primzahlen

<img style="float: left;" src="resources/img/laptop_icon.png" width=50 height=50 /> <br><br>

Schreibe eine Funktion, die als Parameter eine natürliche Zahl 'n' aufnimmt und alle Primzahlen bis n als Liste ausgibt.


In [ ]:
# Füge deinen Code hier ein.

### Größter gemeinsamer Teiler

<img style="float: left;" src="resources/img/laptop_icon.png" width=50 height=50 /> <br><br>

Schreibe eine Funktion, die den größten gemeinsamen Teiler zweier natürlicher Zahlen ausgibt.

In [ ]:
# Füge deinen Code hier ein.

### Primfaktorzerlegung

<img style="float: left;" src="resources/img/laptop_icon.png" width=50 height=50 /> <br><br>

Schreibe eine Funktion, die eine natürliche Zahl in ihre Primfaktoren zerlegt.

In [ ]:
# Füge deinen Code hier ein.

### Permutationen einer Zahlenliste

<img style="float: left;" src="resources/img/laptop_icon.png" width=50 height=50 /> <br><br>

Schreibe eine Funktion, die alle Permutation einer Zahlenliste zurückgibt.

In [ ]:
zahlen = [0, 1, 2, 3, 4, 5]

# Füge deinen Code hier ein.

### Binäres Palindrom

<img style="float: left;" src="resources/img/laptop_icon.png" width=50 height=50 /> <br><br>
Schreibe eine Funktion, die eine Zahl in ihre binäre Darstellung umwandelt und anschließend prüft, ob diese Zahl ein Palindrom (in der binären Darstellung) ist.

In [12]:
# Füge deinen Code hier ein.